/****************************************************************************/
/*                                                                          */
/*  Copyright (C) 2019                                                      */
/*          （株）ＮＴＴデータ                                              */
/*           第三金融事業本部 戦略ビジネス本部　システム企画担当            */
/*                                                                          */
/*  収容物  ＣＯＮＴＩＭＩＸＥ    VirtualPrinterDriver                      */
/*                                                                          */
/****************************************************************************/
/*--------------------------------------------------------------------------*/
/*〈対象業務名〉                                                            */
/*〈対象業務ＩＤ〉                                                          */
/*〈モジュール名〉                  Resources.Designer.cs                   */
/*〈モジュールＩＤ〉                                                        */
/*〈モジュール通番〉                                                        */
/*--------------------------------------------------------------------------*/
/* ＜適応ＯＳ＞                     Windows 10 XXX                          */
/* ＜開発環境＞                     Microsoft Visual Studio 2017            */
/*--------------------------------------------------------------------------*/
/* ＜開発システム名＞               ＣＯＮＴＩＭＩＸＥ                      */
/* ＜開発システム番号＞                                                     */
/*--------------------------------------------------------------------------*/
/* ＜開発担当名＞                   システム企画担当                        */
/* ＜電話番号＞                     050-5546-2418                           */
/*--------------------------------------------------------------------------*/
/* ＜設計者名＞                     範                                      */
/* ＜設計年月日＞                   2019年02月19日　　　　　                */
/* ＜設計修正者名＞                                                         */
/* ＜設計修正年月日及び修正ＩＤ＞                                           */
/*--------------------------------------------------------------------------*/
/* ＜ソース作成者名＞               範                                      */
/* ＜ソース作成年月日＞             2019年02月19日　　　　　                */
/* ＜ソース修正者名＞                                                       */
/* ＜ソース修正年月日及び修正ＩＤ＞                                         */
/*--------------------------------------------------------------------------*/

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMPrint.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VMPrint.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 店番を4桁の数字で入力してください。 的本地化字符串。
        /// </summary>
        internal static string ERROR_BRANCH_NO {
            get {
                return ResourceManager.GetString("ERROR_BRANCH_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 エラー 的本地化字符串。
        /// </summary>
        internal static string ERROR_CAPTION {
            get {
                return ResourceManager.GetString("ERROR_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not create the output file. 的本地化字符串。
        /// </summary>
        internal static string ERROR_COULD_NOT_WRITE {
            get {
                return ResourceManager.GetString("ERROR_COULD_NOT_WRITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VM Printer 的本地化字符串。
        /// </summary>
        internal static string ERROR_DIALOG_CAPTION {
            get {
                return ResourceManager.GetString("ERROR_DIALOG_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is being used by another process. 的本地化字符串。
        /// </summary>
        internal static string ERROR_FILE_INUSE {
            get {
                return ResourceManager.GetString("ERROR_FILE_INUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output filename is longer than 260 characters, or blank. 的本地化字符串。
        /// </summary>
        internal static string ERROR_FILENAME_IS_LONGER {
            get {
                return ResourceManager.GetString("ERROR_FILENAME_IS_LONGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ghostscript error code {0}. 的本地化字符串。
        /// </summary>
        internal static string ERROR_GHOSTSCRIPT_CONVERSION {
            get {
                return ResourceManager.GetString("ERROR_GHOSTSCRIPT_CONVERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is in use. 的本地化字符串。
        /// </summary>
        internal static string ERROR_IN_USE {
            get {
                return ResourceManager.GetString("ERROR_IN_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insufficient privileges to either create or delete {0} 的本地化字符串。
        /// </summary>
        internal static string ERROR_INSUFFICIENT_PRIVILEGES {
            get {
                return ResourceManager.GetString("ERROR_INSUFFICIENT_PRIVILEGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 機番を3桁の英数字で入力してください。 的本地化字符串。
        /// </summary>
        internal static string ERROR_MACHINE_NO {
            get {
                return ResourceManager.GetString("ERROR_MACHINE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出力ディレクトリの設定値が正しくありません。 的本地化字符串。
        /// </summary>
        internal static string ERROR_PDF_DIRECTORY_INVALID {
            get {
                return ResourceManager.GetString("ERROR_PDF_DIRECTORY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出力ディレクトリを入力してください。 的本地化字符串。
        /// </summary>
        internal static string ERROR_PDF_DIRECTORY_NOTINPUT {
            get {
                return ResourceManager.GetString("ERROR_PDF_DIRECTORY_NOTINPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was a PDF generation error. 的本地化字符串。
        /// </summary>
        internal static string ERROR_PDF_GENERATION {
            get {
                return ResourceManager.GetString("ERROR_PDF_GENERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 プリンター名を入力してください。 的本地化字符串。
        /// </summary>
        internal static string ERROR_PRINT_NAME_NOTINPUT {
            get {
                return ResourceManager.GetString("ERROR_PRINT_NAME_NOTINPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 検索文字列を入力してください。 的本地化字符串。
        /// </summary>
        internal static string ERROR_STYLE_NOTINPUT {
            get {
                return ResourceManager.GetString("ERROR_STYLE_NOTINPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an internal error. Enable tracing for details. 的本地化字符串。
        /// </summary>
        internal static string ERROR_UNEXPECTED_ERROR {
            get {
                return ResourceManager.GetString("ERROR_UNEXPECTED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception message: 的本地化字符串。
        /// </summary>
        internal static string EXCEPTION_MESSAGE_PREFIX {
            get {
                return ResourceManager.GetString("EXCEPTION_MESSAGE_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pdf files (*.pdf)|*.pdf 的本地化字符串。
        /// </summary>
        internal static string FILENAME_FILTER {
            get {
                return ResourceManager.GetString("FILENAME_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VM Printer 的本地化字符串。
        /// </summary>
        internal static string FILENAME_TITLE {
            get {
                return ResourceManager.GetString("FILENAME_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon pdf {
            get {
                object obj = ResourceManager.GetObject("pdf", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 {0} could not be deleted. 的本地化字符串。
        /// </summary>
        internal static string WARN_FILE_NOT_DELETED {
            get {
                return ResourceManager.GetString("WARN_FILE_NOT_DELETED", resourceCulture);
            }
        }
    }
}
