/****************************************************************************/
/*                                                                          */
/*  Copyright (C) 2019                                                      */
/*          （株）ＮＴＴデータ                                              */
/*           第三金融事業本部 戦略ビジネス本部　システム企画担当            */
/*                                                                          */
/*  収容物  ＣＯＮＴＩＭＩＸＥ    VirtualPrinterDriver                      */
/*                                                                          */
/****************************************************************************/
/*--------------------------------------------------------------------------*/
/*〈対象業務名〉                                                            */
/*〈対象業務ＩＤ〉                                                          */
/*〈モジュール名〉                  Resources.Designer.cs                   */
/*〈モジュールＩＤ〉                                                        */
/*〈モジュール通番〉                                                        */
/*--------------------------------------------------------------------------*/
/* ＜適応ＯＳ＞                     Windows 10 XXX                          */
/* ＜開発環境＞                     Microsoft Visual Studio 2017            */
/*--------------------------------------------------------------------------*/
/* ＜開発システム名＞               ＣＯＮＴＩＭＩＸＥ                      */
/* ＜開発システム番号＞                                                     */
/*--------------------------------------------------------------------------*/
/* ＜開発担当名＞                   システム企画担当                        */
/* ＜電話番号＞                     050-5546-2418                           */
/*--------------------------------------------------------------------------*/
/* ＜設計者名＞                     範                                      */
/* ＜設計年月日＞                   2019年02月19日　　　　　                */
/* ＜設計修正者名＞                                                         */
/* ＜設計修正年月日及び修正ＩＤ＞                                           */
/*--------------------------------------------------------------------------*/
/* ＜ソース作成者名＞               範                                      */
/* ＜ソース作成年月日＞             2019年02月19日　　　　　                */
/* ＜ソース修正者名＞                                                       */
/* ＜ソース修正年月日及び修正ＩＤ＞                                         */
/*--------------------------------------------------------------------------*/

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMPrintCore.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VMPrintCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Frank Fan 的本地化字符串。
        /// </summary>
        internal static string DRIVER_MANUFACTURER {
            get {
                return ResourceManager.GetString("DRIVER_MANUFACTURER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VM Print Virtual Printer 的本地化字符串。
        /// </summary>
        internal static string DRIVER_NAME {
            get {
                return ResourceManager.GetString("DRIVER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Printer drivers copied or already exist. 的本地化字符串。
        /// </summary>
        internal static string DRV_ALREADYEXISTS {
            get {
                return ResourceManager.GetString("DRV_ALREADYEXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not retrieve printer driver directory. 的本地化字符串。
        /// </summary>
        internal static string DRV_DIR_NOT_RETRIEVE {
            get {
                return ResourceManager.GetString("DRV_DIR_NOT_RETRIEVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Printer driver installed. 的本地化字符串。
        /// </summary>
        internal static string DRV_INSTALLED {
            get {
                return ResourceManager.GetString("DRV_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not enumerate printer drivers. 的本地化字符串。
        /// </summary>
        internal static string DRV_NOT_ENUMERATE {
            get {
                return ResourceManager.GetString("DRV_NOT_ENUMERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Call to EnumPrinterDrivers in winspool.drv succeeded with a zero size buffer - unexpected error. 的本地化字符串。
        /// </summary>
        internal static string ENUMDRV_ZERO_SIZE_BUFFER {
            get {
                return ResourceManager.GetString("ENUMDRV_ZERO_SIZE_BUFFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Call to EnumMonitors in winspool.drv succeeded with a zero size buffer - unexpected error. 的本地化字符串。
        /// </summary>
        internal static string ENUMMONITOR_ZERO_SIZE_BUFFER {
            get {
                return ResourceManager.GetString("ENUMMONITOR_ZERO_SIZE_BUFFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Destination file {0} was not copied/created - it already exists. 的本地化字符串。
        /// </summary>
        internal static string FILENOTCOPIED_ALREADYEXISTS {
            get {
                return ResourceManager.GetString("FILENOTCOPIED_ALREADYEXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Printer driver file was not copied. Exception message: {0} 的本地化字符串。
        /// </summary>
        internal static string FILENOTCOPIED_PRINTERDRIVER {
            get {
                return ResourceManager.GetString("FILENOTCOPIED_PRINTERDRIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is being used by another process. File was not deleted. 的本地化字符串。
        /// </summary>
        internal static string FILENOTDELETED_INUSE {
            get {
                return ResourceManager.GetString("FILENOTDELETED_INUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is read-only, or its file permissions do not allow for deletion. 的本地化字符串。
        /// </summary>
        internal static string FILENOTDELETED_UNAUTHORIZED {
            get {
                return ResourceManager.GetString("FILENOTDELETED_UNAUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VMPrint_Driver0101 的本地化字符串。
        /// </summary>
        internal static string HARDWARE_ID {
            get {
                return ResourceManager.GetString("HARDWARE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port configuration failed. 的本地化字符串。
        /// </summary>
        internal static string INFO_INSTALLCONFIGPORT_FAILED {
            get {
                return ResourceManager.GetString("INFO_INSTALLCONFIGPORT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not copy printer driver files. 的本地化字符串。
        /// </summary>
        internal static string INFO_INSTALLCOPYDRIVER_FAILED {
            get {
                return ResourceManager.GetString("INFO_INSTALLCOPYDRIVER_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not add redirected port. 的本地化字符串。
        /// </summary>
        internal static string INFO_INSTALLPORT_FAILED {
            get {
                return ResourceManager.GetString("INFO_INSTALLPORT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port monitor installation failed. 的本地化字符串。
        /// </summary>
        internal static string INFO_INSTALLPORTMONITOR_FAILED {
            get {
                return ResourceManager.GetString("INFO_INSTALLPORTMONITOR_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not add printer. 的本地化字符串。
        /// </summary>
        internal static string INFO_INSTALLPRINTER_FAILED {
            get {
                return ResourceManager.GetString("INFO_INSTALLPRINTER_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Printer driver installation failed. 的本地化字符串。
        /// </summary>
        internal static string INFO_INSTALLPRINTERDRIVER_FAILED {
            get {
                return ResourceManager.GetString("INFO_INSTALLPRINTERDRIVER_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Partial uninstallation failure. Function {0} returned false. 的本地化字符串。
        /// </summary>
        internal static string INSTALL_ROLLBACK_FAILURE_AT_FUNCTION {
            get {
                return ResourceManager.GetString("INSTALL_ROLLBACK_FAILURE_AT_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port monitor successfully installed. 的本地化字符串。
        /// </summary>
        internal static string MONITOR_INSTALLED {
            get {
                return ResourceManager.GetString("MONITOR_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not enumerate port monitors. 的本地化字符串。
        /// </summary>
        internal static string MONITOR_NOT_ENUMERATE {
            get {
                return ResourceManager.GetString("MONITOR_NOT_ENUMERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not remove port monitor dll. 的本地化字符串。
        /// </summary>
        internal static string MONITOR_NOT_REMOVE {
            get {
                return ResourceManager.GetString("MONITOR_NOT_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not enable 64-bit file system redirection. 的本地化字符串。
        /// </summary>
        internal static string NATIVE_COULDNOTENABLE64REDIRECTION {
            get {
                return ResourceManager.GetString("NATIVE_COULDNOTENABLE64REDIRECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not revert 64-bit file system redirection. 的本地化字符串。
        /// </summary>
        internal static string NATIVE_COULDNOTREVERT64REDIRECTION {
            get {
                return ResourceManager.GetString("NATIVE_COULDNOTREVERT64REDIRECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redirection port added. 的本地化字符串。
        /// </summary>
        internal static string PORT_ADDED {
            get {
                return ResourceManager.GetString("PORT_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port monitor {0} already installed. 的本地化字符串。
        /// </summary>
        internal static string PORT_ALREADY_INSTALLED {
            get {
                return ResourceManager.GetString("PORT_ALREADY_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local Port 的本地化字符串。
        /// </summary>
        internal static string PORT_DESCRIPTION {
            get {
                return ResourceManager.GetString("PORT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not add port monitor {0} 的本地化字符串。
        /// </summary>
        internal static string PORT_NOT_ADDED {
            get {
                return ResourceManager.GetString("PORT_NOT_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 winprint 的本地化字符串。
        /// </summary>
        internal static string PRINT_PROCESOR {
            get {
                return ResourceManager.GetString("PRINT_PROCESOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VM Print 的本地化字符串。
        /// </summary>
        internal static string PRINTER_NAME {
            get {
                return ResourceManager.GetString("PRINTER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not add port configuration to registry. Exception message: {0} 的本地化字符串。
        /// </summary>
        internal static string REGISTRYCONFIG_NOT_ADDED {
            get {
                return ResourceManager.GetString("REGISTRYCONFIG_NOT_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not delete port configuration from registry. Exception message: {0} 的本地化字符串。
        /// </summary>
        internal static string REGISTRYCONFIG_NOT_DELETED {
            get {
                return ResourceManager.GetString("REGISTRYCONFIG_NOT_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not add VM printer driver. 的本地化字符串。
        /// </summary>
        internal static string VM_DRV_NOT_ADDED {
            get {
                return ResourceManager.GetString("VM_DRV_NOT_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not remove VM Print printer driver. 的本地化字符串。
        /// </summary>
        internal static string VM_DRV_NOT_REMOVE {
            get {
                return ResourceManager.GetString("VM_DRV_NOT_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not add VM printer. 的本地化字符串。
        /// </summary>
        internal static string VM_NOT_ADDED {
            get {
                return ResourceManager.GetString("VM_NOT_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not delete VM virtual printer. 的本地化字符串。
        /// </summary>
        internal static string VM_NOT_DELETE {
            get {
                return ResourceManager.GetString("VM_NOT_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Printer configured. 的本地化字符串。
        /// </summary>
        internal static string VM_PRINT_CONFIGURED {
            get {
                return ResourceManager.GetString("VM_PRINT_CONFIGURED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Virtual printer installed. 的本地化字符串。
        /// </summary>
        internal static string VM_PRINT_INSTALLED {
            get {
                return ResourceManager.GetString("VM_PRINT_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Win32 error code {0}. 的本地化字符串。
        /// </summary>
        internal static string WIN32ERROR {
            get {
                return ResourceManager.GetString("WIN32ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not disable Wow64 file system redirection. 的本地化字符串。
        /// </summary>
        internal static string WOW64_NOT_DISABLE {
            get {
                return ResourceManager.GetString("WOW64_NOT_DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not reenable Wow64 file system redirection. 的本地化字符串。
        /// </summary>
        internal static string WOW64_NOT_REENABLE {
            get {
                return ResourceManager.GetString("WOW64_NOT_REENABLE", resourceCulture);
            }
        }
    }
}
