//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMPrintCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VMPrintCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amos Xia.
        /// </summary>
        internal static string DRIVER_MANUFACTURER {
            get {
                return ResourceManager.GetString("DRIVER_MANUFACTURER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM Print Virtual Printer.
        /// </summary>
        internal static string DRIVER_NAME {
            get {
                return ResourceManager.GetString("DRIVER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer drivers copied or already exist..
        /// </summary>
        internal static string DRV_ALREADYEXISTS {
            get {
                return ResourceManager.GetString("DRV_ALREADYEXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve printer driver directory..
        /// </summary>
        internal static string DRV_DIR_NOT_RETRIEVE {
            get {
                return ResourceManager.GetString("DRV_DIR_NOT_RETRIEVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer driver installed..
        /// </summary>
        internal static string DRV_INSTALLED {
            get {
                return ResourceManager.GetString("DRV_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not enumerate printer drivers..
        /// </summary>
        internal static string DRV_NOT_ENUMERATE {
            get {
                return ResourceManager.GetString("DRV_NOT_ENUMERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to EnumPrinterDrivers in winspool.drv succeeded with a zero size buffer - unexpected error..
        /// </summary>
        internal static string ENUMDRV_ZERO_SIZE_BUFFER {
            get {
                return ResourceManager.GetString("ENUMDRV_ZERO_SIZE_BUFFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to EnumMonitors in winspool.drv succeeded with a zero size buffer - unexpected error..
        /// </summary>
        internal static string ENUMMONITOR_ZERO_SIZE_BUFFER {
            get {
                return ResourceManager.GetString("ENUMMONITOR_ZERO_SIZE_BUFFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination file {0} was not copied/created - it already exists..
        /// </summary>
        internal static string FILENOTCOPIED_ALREADYEXISTS {
            get {
                return ResourceManager.GetString("FILENOTCOPIED_ALREADYEXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer driver file was not copied. Exception message: {0}.
        /// </summary>
        internal static string FILENOTCOPIED_PRINTERDRIVER {
            get {
                return ResourceManager.GetString("FILENOTCOPIED_PRINTERDRIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is being used by another process. File was not deleted..
        /// </summary>
        internal static string FILENOTDELETED_INUSE {
            get {
                return ResourceManager.GetString("FILENOTDELETED_INUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is read-only, or its file permissions do not allow for deletion..
        /// </summary>
        internal static string FILENOTDELETED_UNAUTHORIZED {
            get {
                return ResourceManager.GetString("FILENOTDELETED_UNAUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VMPrint_Driver0101.
        /// </summary>
        internal static string HARDWARE_ID {
            get {
                return ResourceManager.GetString("HARDWARE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port configuration failed..
        /// </summary>
        internal static string INFO_INSTALLCONFIGPORT_FAILED {
            get {
                return ResourceManager.GetString("INFO_INSTALLCONFIGPORT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not copy printer driver files..
        /// </summary>
        internal static string INFO_INSTALLCOPYDRIVER_FAILED {
            get {
                return ResourceManager.GetString("INFO_INSTALLCOPYDRIVER_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add redirected port..
        /// </summary>
        internal static string INFO_INSTALLPORT_FAILED {
            get {
                return ResourceManager.GetString("INFO_INSTALLPORT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port monitor installation failed..
        /// </summary>
        internal static string INFO_INSTALLPORTMONITOR_FAILED {
            get {
                return ResourceManager.GetString("INFO_INSTALLPORTMONITOR_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add printer..
        /// </summary>
        internal static string INFO_INSTALLPRINTER_FAILED {
            get {
                return ResourceManager.GetString("INFO_INSTALLPRINTER_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer driver installation failed..
        /// </summary>
        internal static string INFO_INSTALLPRINTERDRIVER_FAILED {
            get {
                return ResourceManager.GetString("INFO_INSTALLPRINTERDRIVER_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial uninstallation failure. Function {0} returned false..
        /// </summary>
        internal static string INSTALL_ROLLBACK_FAILURE_AT_FUNCTION {
            get {
                return ResourceManager.GetString("INSTALL_ROLLBACK_FAILURE_AT_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port monitor successfully installed..
        /// </summary>
        internal static string MONITOR_INSTALLED {
            get {
                return ResourceManager.GetString("MONITOR_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not enumerate port monitors..
        /// </summary>
        internal static string MONITOR_NOT_ENUMERATE {
            get {
                return ResourceManager.GetString("MONITOR_NOT_ENUMERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove port monitor dll..
        /// </summary>
        internal static string MONITOR_NOT_REMOVE {
            get {
                return ResourceManager.GetString("MONITOR_NOT_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not enable 64-bit file system redirection..
        /// </summary>
        internal static string NATIVE_COULDNOTENABLE64REDIRECTION {
            get {
                return ResourceManager.GetString("NATIVE_COULDNOTENABLE64REDIRECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not revert 64-bit file system redirection..
        /// </summary>
        internal static string NATIVE_COULDNOTREVERT64REDIRECTION {
            get {
                return ResourceManager.GetString("NATIVE_COULDNOTREVERT64REDIRECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirection port added..
        /// </summary>
        internal static string PORT_ADDED {
            get {
                return ResourceManager.GetString("PORT_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port monitor {0} already installed..
        /// </summary>
        internal static string PORT_ALREADY_INSTALLED {
            get {
                return ResourceManager.GetString("PORT_ALREADY_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Port.
        /// </summary>
        internal static string PORT_DESCRIPTION {
            get {
                return ResourceManager.GetString("PORT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add port monitor {0}.
        /// </summary>
        internal static string PORT_NOT_ADDED {
            get {
                return ResourceManager.GetString("PORT_NOT_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to winprint.
        /// </summary>
        internal static string PRINT_PROCESOR {
            get {
                return ResourceManager.GetString("PRINT_PROCESOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM Print.
        /// </summary>
        internal static string PRINTER_NAME {
            get {
                return ResourceManager.GetString("PRINTER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add port configuration to registry. Exception message: {0}.
        /// </summary>
        internal static string REGISTRYCONFIG_NOT_ADDED {
            get {
                return ResourceManager.GetString("REGISTRYCONFIG_NOT_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete port configuration from registry. Exception message: {0}.
        /// </summary>
        internal static string REGISTRYCONFIG_NOT_DELETED {
            get {
                return ResourceManager.GetString("REGISTRYCONFIG_NOT_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add VM printer driver. .
        /// </summary>
        internal static string VM_DRV_NOT_ADDED {
            get {
                return ResourceManager.GetString("VM_DRV_NOT_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove VM Print printer driver. .
        /// </summary>
        internal static string VM_DRV_NOT_REMOVE {
            get {
                return ResourceManager.GetString("VM_DRV_NOT_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add VM printer. .
        /// </summary>
        internal static string VM_NOT_ADDED {
            get {
                return ResourceManager.GetString("VM_NOT_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete VM virtual printer..
        /// </summary>
        internal static string VM_NOT_DELETE {
            get {
                return ResourceManager.GetString("VM_NOT_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer configured..
        /// </summary>
        internal static string VM_PRINT_CONFIGURED {
            get {
                return ResourceManager.GetString("VM_PRINT_CONFIGURED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual printer installed..
        /// </summary>
        internal static string VM_PRINT_INSTALLED {
            get {
                return ResourceManager.GetString("VM_PRINT_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win32 error code {0}..
        /// </summary>
        internal static string WIN32ERROR {
            get {
                return ResourceManager.GetString("WIN32ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not disable Wow64 file system redirection..
        /// </summary>
        internal static string WOW64_NOT_DISABLE {
            get {
                return ResourceManager.GetString("WOW64_NOT_DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not reenable Wow64 file system redirection..
        /// </summary>
        internal static string WOW64_NOT_REENABLE {
            get {
                return ResourceManager.GetString("WOW64_NOT_REENABLE", resourceCulture);
            }
        }
    }
}
